version: "2"
services:
  db:
    container_name: db
    image: bitnami/postgresql:12
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "db"
      POSTGRES_PASSWORD: "db"
      DISABLE_WELCOME_MESSAGE: "true"
    ports:
      - "5432:5432"
    networks:
      - test
networks:
  test:
